version: "3"

services:
  adminer:
    image: adminer:latest
    depends_on:
      - db
    networks:
      main:
        aliases:
          - adminer
  proxy:
    image: nginx:mainline-alpine
    depends_on:
      #- api
      - adminer
    ports:
      - "8080:8080"
    volumes:
      - ./conf/proxy.conf:/etc/nginx/conf.d/default.conf
    networks:
      main:
        aliases:
          - proxy
