version: "3"

services:
  db:
    image: postgres:latest
    env_file:
      - db.env
    ports:
      - "5432:5432"
    networks:
      main:
        aliases:
          - db
networks:
  main:
    driver: bridge
